import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import SearchParam from "../component/SearchParams"
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>UEFA CHAMPIONS LEAGUE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


 
        <SearchParam/>
       
    </div>
  )
}
